-- MySQL Script generated by MySQL Workbench
-- Mon Nov  3 07:32:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Optic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Optic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Optic` DEFAULT CHARACTER SET utf8 ;
USE `Optic` ;

-- -----------------------------------------------------
-- Table `Optic`.`Suplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optic`.`Suplier` (
  `suplier_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `street` VARCHAR(100) NULL,
  `streetInt` INT NULL,
  `floor` INT NULL,
  `door` INT NULL,
  `city` VARCHAR(85) NULL,
  `postal code` INT NULL,
  `country` VARCHAR(56) NULL,
  `phone` INT NULL,
  `fax` VARCHAR(45) NULL,
  `nif` VARCHAR(45) NULL,
  PRIMARY KEY (`suplier_id`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optic`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optic`.`Brand` (
  `brand_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `suplier_id` INT NOT NULL,
  PRIMARY KEY (`brand_id`),
  INDEX `suplier_id_idx` (`suplier_id` ASC) VISIBLE,
  CONSTRAINT `suplier_id`
    FOREIGN KEY (`suplier_id`)
    REFERENCES `Optic`.`Suplier` (`suplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optic`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optic`.`Glasses` (
  `glasses_id` INT NOT NULL AUTO_INCREMENT,
  `brand_id` INT NOT NULL,
  `lens_graduation_r` DECIMAL(4,2) NULL,
  `lens_graduation_l` DECIMAL(4,2) NULL,
  `frame_type` ENUM('floating', 'plastic', 'metal') NULL,
  `color_frame` VARCHAR(45) NULL,
  `color_lens_r` VARCHAR(45) NULL,
  `color_lens_l` VARCHAR(45) NULL,
  `price` DECIMAL(8,2) NULL,
  PRIMARY KEY (`glasses_id`),
  INDEX `brand_id_idx` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `brand_id`
    FOREIGN KEY (`brand_id`)
    REFERENCES `Optic`.`Brand` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optic`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optic`.`Client` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `direction` VARCHAR(100) NULL,
  `phone` INT NULL,
  `email` VARCHAR(45) NULL,
  `register_date` DATE NULL,
  `recomended_for` INT NULL,
  PRIMARY KEY (`client_id`),
  INDEX `cliente_id_idx` (`recomended_for` ASC) VISIBLE,
  CONSTRAINT `cliente_id`
    FOREIGN KEY (`recomended_for`)
    REFERENCES `Optic`.`Client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optic`.`worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optic`.`worker` (
  `worker_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `subnames` VARCHAR(45) NULL,
  PRIMARY KEY (`worker_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optic`.`Sell`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optic`.`Sell` (
  `sell_id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `worker_id` INT NOT NULL,
  `glasses_id` INT NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`sell_id`),
  INDEX `client_id_idx` (`client_id` ASC) VISIBLE,
  INDEX `worker_id_idx` (`worker_id` ASC) VISIBLE,
  INDEX `glasses_id_idx` (`glasses_id` ASC) VISIBLE,
  CONSTRAINT `client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `Optic`.`Client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `worker_id`
    FOREIGN KEY (`worker_id`)
    REFERENCES `Optic`.`worker` (`worker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `glasses_id`
    FOREIGN KEY (`glasses_id`)
    REFERENCES `Optic`.`Glasses` (`glasses_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
