-- MySQL Script generated by MySQL Workbench
-- Mon Nov  3 13:11:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`Province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Province` (
  `province_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`province_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`City` (
  `idCity` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`idCity`),
  INDEX `province_id_idx` (`province_id` ASC) VISIBLE,
  CONSTRAINT `province_city_id`
    FOREIGN KEY (`province_id`)
    REFERENCES `Pizzeria`.`Province` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`idClient`),
  INDEX `idCity_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `idCity_client`
    FOREIGN KEY (`city_id`)
    REFERENCES `Pizzeria`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Store` (
  `idStore` INT NOT NULL AUTO_INCREMENT,
  `adress` VARCHAR(45) NOT NULL,
  `postal_code` INT NOT NULL,
  `city_id` INT NOT NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`idStore`),
  INDEX `city_id_idx` (`city_id` ASC) VISIBLE,
  INDEX `province_id_idx` (`province_id` ASC) VISIBLE,
  CONSTRAINT `city_id_store`
    FOREIGN KEY (`city_id`)
    REFERENCES `Pizzeria`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `province_id_store`
    FOREIGN KEY (`province_id`)
    REFERENCES `Pizzeria`.`Province` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `phone` INT NULL,
  `role` ENUM('cook', 'delivery') NOT NULL,
  `store_id` INT NULL,
  PRIMARY KEY (`idEmployee`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE,
  INDEX `store_id_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `store_id_employee`
    FOREIGN KEY (`store_id`)
    REFERENCES `Pizzeria`.`Store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `image` VARCHAR(255) NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `Pizzeria`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `order_datetime` DATETIME NOT NULL,
  `delivery_type` ENUM('home', 'pickup') NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `delivery_employee_id` INT NULL,
  `delivery_datetime` DATETIME NULL,
  PRIMARY KEY (`order_id`),
  INDEX `store_id_idx` (`store_id` ASC) VISIBLE,
  INDEX `employee_id_idx` (`delivery_employee_id` ASC) VISIBLE,
  INDEX `client_id_order_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `client_id_order`
    FOREIGN KEY (`client_id`)
    REFERENCES `Pizzeria`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `store_id_order`
    FOREIGN KEY (`store_id`)
    REFERENCES `Pizzeria`.`Store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employee_id_order`
    FOREIGN KEY (`delivery_employee_id`)
    REFERENCES `Pizzeria`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`order_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`order_product` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`product_id`, `order_id`),
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `Pizzeria`.`Order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `Pizzeria`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
